import numpy as np
import math
from collections import deque

N, M = 10, 20  # Dimensions for the Map
SIGNAL_THRESHOLD = 10  # The distance that if exceeded connection is lost

ROBOTS_POSITIONS = [(0, 0), (0, 1)]
R = len(ROBOTS_POSITIONS)  # Number of Robots
K = 5  # Number of steps in the generated path

COVERAGE_WEIGHT = 0.5
SIGNAL_STRENGTH_WEIGHT = (1 - COVERAGE_WEIGHT)  # Weights for each Decision Variable

Map = np.zeros((N, M))


# def create_random_initialization():
#     """
#     initializes Robots in random positions in the map while maintaining map boundaries N, M
#     :return:
#     Array of tuples of initial Robot Positions
#     """
#     positions = []
#     for _ in range(R):
#         x = np.random.randint(0, N)
#         y = np.random.randint(0, M)
#         positions.append((x, y))
#     return positions

def create_dummy_solution():
    """
    returns a random path for each robot according to the number of robots,
    :return:
    path_array (array of size, R robots, K time steps)
    """
    path_array = [[(1,0),(2,0),(3,0),(4,0),(5,0)],[(0,1),(0,2),(0,3),(0,4),(0,5)]]
    return np.array(path_array, dtype=object)


def valid_move(p1, p2):
    """Check if p2 is the same cell or one of 4-connected adjacent cells."""
    dx = abs(p1[0] - p2[0])
    dy = abs(p1[1] - p2[1])
    return (dx + dy == 1) or (dx == 0 and dy == 0)


def euclidean_distance(p1, p2):
    return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)


def check_signal_connection(path_at_index):
    adj_list = np.zeros((R, R))
    for i in range(R):
        for j in range(i + 1, R):
            if euclidean_distance(path_at_index[i], path_at_index[j]) <= SIGNAL_THRESHOLD:
                adj_list[i][j] = 1
                adj_list[j][i] = 1
    visited = set()
    queue = deque([0])
    visited.add(0)

    while queue:
        node = queue.popleft()

        for neighbor in range(R):
            if adj_list[node][neighbor] == 1 and neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

    return len(visited) == R


def get_signal_cost(path_at_last_index):
    cost = 0
    for i in range(R):
        for j in range(i + 1, R):
            cost += euclidean_distance(path_at_last_index[i], path_at_last_index[j])
    return cost


def cost_function(path_array):  # [[(0,1),(0,2)], [(1,2),(0,2)]]
    """
        path_array: 2D list or numpy array of size R x K that contains all paths generated for one iteration

        When a path (possible solution is generated by simulation model), it checks the movement constraints then if those are passed
        it checks if the new positions does not exceed signal threshold

        Returns: a numeric value representing the cost of choosing these paths, if the paths are invalid it returns -1
    """
    visited = set()
    visited_unexplored = set()
    for r in range(R):
        # ---  First Robot Path ---
        path = path_array[r]

        # --- First step movement check ---
        first_step = path[0]
        start_pos = ROBOTS_POSITIONS[r]
        if not valid_move(start_pos, first_step):
            print("non valid first step")
            return -1

        # --- Check Validation for K Steps ---
        for step_idx, (x, y) in enumerate(path):

            # --- Boundary check ---
            if not (0 <= x < N and 0 <= y < M):
                print("non valid boundary")
                return -1

            # --- Obstacle check ---
            if Map[x, y] == 2:
                print("obstacle detected")
                return -1

            # --- Overlap check per timestep ---
            if (x, y, step_idx) in visited:
                print("overlap check")
                return -1
            visited.add((x, y, step_idx))

            # --- Movement check ---
            if step_idx > 0:
                prev = path[step_idx - 1]
                if not valid_move(prev, (x, y)):
                    print("invalid move")
                    return -1

            if Map[x][y] == 0:
                visited_unexplored.add((x, y))

    path_at_last_index = []
    for i in range(K):
        path_at_index = []
        for j in range(R):
            path_at_index.append(path_array[j][i])
            if i == K - 1:
                path_at_last_index.append(path_array[j][i])
        if check_signal_connection(path_at_index) is False:
            return -100

    cost = COVERAGE_WEIGHT * len(visited_unexplored) + SIGNAL_STRENGTH_WEIGHT * get_signal_cost(path_at_last_index)
    return cost


if __name__ == "__main__":
    # create random positions of robots
    # create dummy solution
    path_array = create_dummy_solution()
    print(cost_function(path_array))
